### ISSUE TITLE
Add a prefix to exported names

### ISSUE THREAD

**Issue by chirsz-ever** [ulfjack/ryu#206] opened 2021-09-17 16:05 UTC
It would be troublesome to export too simple names like `s2d`. `ryu_s2d` would be better.

**Comment by cppguru** [comment] 2021-09-17 17:12
We are in violent agreement on that.  But that change could be unconditional.

**Comment by ecorm** [comment] 2021-09-17 17:16
I've barked up that tree before https://github.com/ulfjack/ryu/issues/148

**Comment by cppguru** [comment] 2021-09-17 17:21
@ecorm Hehe.  I read your motivation there.  Welcome to the club. :D

**Comment by cppguru** [comment] 2021-09-17 17:22
But seriously those prefixes would be awesome.  I prefixed the stuff I added to our fork.

**Comment by ulfjack** [comment] 2021-09-17 22:32
Closing as a dupe of #148.

**Closed by ulfjack** 2021-09-17 22:32 UTC

**Comment by chirsz-ever** [comment] 2021-09-18 02:06
> I've barked up that tree before #148

Sorry, it's my neglect.
